title: proofdict
email: azuciao@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Proofdict is a dictionary project.
 It aim to create a dictionary that is consist of tiny dictionary.
baseurl: "/proofdict" # the subpath of your site, e.g. /blog
url: "https://proofdict.github.io/proofdict" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: azu_re
github_username:  proofdict

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
